version: '3'

services:
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "3000:80"
      - "443:443"
    volumes:
      - ./backend/:/var/www
      - ./backend/nginx/:/etc/nginx/conf.d/
    networks:
      - app-network

  app:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    container_name: meu-campeonato-backend
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./backend/:/var/www
      - ./backend/vendor:/var/www/vendor
    networks:
      - app-network

  db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: meu-campeonato-DB
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: meu_campeonato
      MYSQL_ROOT_PASSWORD: password
    networks:
      - app-network

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
    networks:
      - app-network

  frontend:
    build:
        context: .
        dockerfile: ./frontend/Dockerfile
    container_name: "meu-campeonato-frontend"
    working_dir: /usr/src/app/frontend
    volumes: 
        - ./frontend/:/usr/src/app/frontend 
    ports: 
        - '4200:4200' 
    command: > 
        bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"
    networks:
        - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
